name: Deploy to EC2

on:
  push:
    branches:
      - main # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Deploy the application to EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ssh ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
            set -e

            # Define the project directory
            APP_DIR="/home/${{ env.EC2_USER }}/chat-app"

            # Clone or pull the repository
            if [ ! -d "$APP_DIR" ]; then
              echo "Cloning repository for the first time..."
              git clone https://github.com/budip/budip.git "$APP_DIR"
            fi
            cd "$APP_DIR"
            git fetch origin
            git reset --hard origin/main

            # Install dependencies
            echo "Installing dependencies..."
            npm install --omit=dev

            # Set up environment variables
            echo "OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}" > .env

            # Restart or start the application using PM2
            echo "Restarting application with PM2..."
            pm2 restart chat-app --update-env || pm2 start server.js --name chat-app
          EOF

      # Step 4: Post-deployment cleanup (optional)
      - name: Cleanup SSH key
        run: |
          rm -f ~/.ssh/id_rsa
